# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20170828_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
