# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_remove_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='forecast_period',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='document',
            name='holt_w',
            field=models.CharField(choices=[('linear', 'Linear'), ('additive', 'Additive'), ('multiplicative', 'Multiplicative')], default='additive', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='seasonal_length',
            field=models.IntegerField(default=12),
        ),
    ]
