# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_document1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document1',
        ),
    ]
